--CREATE DATABASE JOB_OPENINGS
USE JOB_OPENINGS
GO

CREATE TABLE USERS (
    _USER_ID int IDENTITY(1,1) NOT NULL,
    _USER_NAME varchar(100) NOT NULL,
	_PASSWORD varchar(100) NOT NULL,
	PRIMARY KEY(_USER_ID)
);
GO

CREATE TABLE DEPARTMENT (
    DEPARTMENT_ID int NOT NULL,
    DEPARTMENT_TITLE varchar(255) NOT NULL,
	PRIMARY KEY(DEPARTMENT_ID)
);
GO

CREATE TABLE _LOCATION (
    LOCATION_ID int NOT NULL,
    LOCATION_TITLE varchar(255) NOT NULL,
	CITY varchar(50) NOT NULL,
	_STATE varchar(50) NOT NULL,
	COUNTRY varchar(50) NOT NULL,
	ZIP nvarchar(50) NOT NULL,
	PRIMARY KEY(LOCATION_ID)
);
GO

CREATE SEQUENCE JOB_SEQUENCE
AS int
START WITH 1
INCREMENT BY 1;
GO

CREATE TABLE JOB (
    JOB_ID int IDENTITY(1,1) NOT NULL,
	CODE varchar(20) CONSTRAINT [DF_JOB_JOB_SEQUENCE]
                      DEFAULT FORMAT((NEXT VALUE FOR JOB_SEQUENCE), 'JOB-0#'),
    JOB_TITLE varchar(50) NOT NULL,
	_DESCRIPTION varchar(100) NOT NULL,
	POSTED_DATE DATETIME NOT NULL,
	CLOSING_DATE DATETIME NOT NULL,
	DAPARTMENT_ID INT references DEPARTMENT(DEPARTMENT_ID),
	LOCATION_ID INT references _LOCATION(LOCATION_ID),
	PRIMARY KEY(JOB_ID)
);
GO

SELECT * FROM JOB;
SELECT * FROM DEPARTMENT;
SELECT * FROM _LOCATION;

